Adverts/urls.py
from django.contrib import admin
# from django.contrib.staticfiles import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.contrib.auth import views as auth_views
from main_app.views import accountsRedirect, ProfileView, UserRegistrationView, UserProfileUpdateView

from main_app import views as main_views
from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'adverts', main_views.AdvertViewSet)
router.register(r'categories', main_views.CategoryViewSet)
router.register(r'cities', main_views.CityViewSet)

urlpatterns = [
    path('', include('main_app.urls')),
    path('api/', include(router.urls)),
    path('api/advert-list/', main_views.AdvertListView.as_view(), name='advert_list'),
    path('api/advert/<int:pk>/', main_views.AdvertDetailView.as_view(), name='advert_detail'),
    path('admin/', admin.site.urls),
    path('accounts/', accountsRedirect, name='accounts'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/profile/', ProfileView.as_view(), name='profile'),
    path('accounts/registration/', UserRegistrationView.as_view(), name='registration'),
    path('accounts/profile/edit/', UserProfileUpdateView.as_view(), name='edit_profile'),
    # path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += staticfiles_urlpatterns()

main_app/urls.py
from django.urls import path
# from django.views.generic import TemplateView

from . import views

app_name = 'main_app'
urlpatterns = [
	path('', views.homPageView.as_view(), name='home'),
]

main_app/models.py
# -*- coding: utf-8 -*-

from django.db import models

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=50, primary_key=True)

    def __str__(self):
            return f'{self.name}'


class City(models.Model):
    name=models.CharField(max_length=50, primary_key=True)

    def __str__(self):
            return f'{self.name}'
            

class Advert(models.Model):
    title=models.CharField(max_length=50)
    description=models.TextField(blank=True)
    city=models.ManyToManyField(City, blank=True, related_name='adverts')
    category=models.ManyToManyField(Category, blank=True, related_name='adverts')
    views=models.IntegerField(default=0)

    def __str__(self):
            return f'{self.title}'

main_app/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User

from django.contrib.auth.password_validation import validate_password

class UserRegistrationForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput,validators=[validate_password])
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']
        required=('email',)

main_app/views.py
# -*- coding: utf-8 -*-

import json

from django.shortcuts import redirect, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.core.serializers import serialize
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DetailView
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.db.models import F

from rest_framework import viewsets
from rest_framework import permissions
from .serializers import CategorySerializer, CitySerializer, AdvertSerializer

from .forms import UserRegistrationForm
from .models import Advert, City, Category

# Create your views here.

class AdvertViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Advert.objects.all()
    serializer_class = AdvertSerializer
    permission_classes = [permissions.IsAdminUser]

class CategoryViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [permissions.IsAdminUser]

class CityViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = City.objects.all()
    serializer_class = CitySerializer
    permission_classes = [permissions.IsAdminUser]

def accountsRedirect(request):
    return HttpResponseRedirect(reverse("main_app:home"))

class homPageView(TemplateView):
    template_name="main_app/home.html"


class AdvertListView(ListView):
    def get_queryset(self):
        return Advert.objects.all().prefetch_related('city', 'category')

    def get(self, request, *args, **kwargs):
        object_list = self.get_queryset()
        data=serialize('json', object_list, cls=DjangoJSONEncoder)
        return JsonResponse({"data": json.loads(data)})


class AdvertDetailView(DetailView):
    model=Advert

    def get(self, request, *args, **kwargs):
        Advert.objects.filter(pk=kwargs["pk"]).update(views=F("views")+1)

        instance = self.get_object()

        data=serialize('json', (instance,), cls=DjangoJSONEncoder)
        return JsonResponse({"data": json.loads(data)[0]})


class ProfileView(LoginRequiredMixin, DetailView):
    template_name="main_app/profile_view.html"
    
    def get_object(self):
        return self.request.user


class UserRegistrationView(CreateView):
    template_name="registration/registration.html"
    model=User
    form_class = UserRegistrationForm
    success_url = reverse_lazy("profile")

    def form_valid(self, form):
        # if self.model.objects.filter(username=form.instance.username).count():
        #     form.add_error('username', 'Already exists!')
        #     return super().form_invalid(form)
        instance=form.instance
        del instance.__dict__['_state']
        user=User.objects.create_user(**instance.__dict__)
        login(self.request, user)
        return redirect(self.success_url)
        

class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name="registration/edit_profile.html"
    model=User
    success_url = reverse_lazy("profile")
    fields=['email', 'first_name', 'last_name']

    def get_object(self):
        return self.request.user

    def post(self, *args, **kwargs):
        if 'cansel' in self.request.POST:
            return HttpResponseRedirect(self.success_url)
        else:
            return super().post(*args, **kwargs)

main_app/templates/main_app/advert_list_view.html
{% extends 'base.html' %}

{% block title %} List of Adverts {% endblock %}

{% block content %}

<div style="text-align:center"><h2>Adverts</h2></div>

<table id="main_block">
    {% for object in object_list %}
    <tr>
        <td id='table_main_column'>{{ object.title }}</td>
        <td><i>{{ object.description }}</i></td>
        <td>{{ object.city }}</td>
        <td>{{ object.category }}</td>
        <td>{{ object.views }}</td>
        <td><a href="{% url 'main_app:advert_detail' pk=object.pk %}">Detail</a>
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

main_app/templates/main_app/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<div style="text-align:center"><h2>Home Page</h2></div>


{% endblock %}

main_app/templates/main_app/profile_view.html
{% extends 'base.html' %}

{% block title %} Profile of {{ object.username }} {% endblock %}

{% block content %}

<div style="text-align:center"><h2>Profile of "{{ object.username }}"</h2></div>

<div id="main_block">
    <p><b>{{ object.username }}</b></p>
    <p>Email adress: {{ object.email }}</p>
    <p>First name: {{ object.first_name }}</p>
    <p>Last name: {{ object.last_name }}</p>
    <p>Date joined: {{ object.date_joined }}</p>
    <p>Last login: {{ object.last_login }}</p>
</div>

<div style="text-align:center">
    <a href="{% url 'password_change' %}">Change Password</a>
    <a href="{% url 'edit_profile' %}">Edit Profile</a>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
  {% block dependencies %}{% endblock %}
  <title>{% block title %}Coding Infinite: Tutorial for Web Login using Django{% endblock title %}</title>
</head>
<body>
  <header>
  	{% block header %}
    <div style="text-align:right">
      {% if request.user.is_authenticated %}
      <a href="{% url 'profile' %}">{{ request.user.username }}</a>
      <a href="{% url 'logout' %}">Logout</a>
      {% else %}
      No authenticated
      <a href="{% url 'registration' %}">Registration</a>
      <a href="{% url 'login' %}">Login</a>
      {% endif %}
    </div>
    {% endblock header %}
  </header>
  <main>
    <span id="navigation">
      {% load main_app_extras %}
      {% for item in request.path|path_to_links %}
      {% if not item.0 %}
      / {{ item.1 }}
      {% else %}
      / <a href="{{ item.0 }}"> {{ item.1 }} </a>
      {% endif %}
      {% endfor %}

      {% block content %}
      {% endblock content %}
    </span>
  </main>
  <footer>
    {% block footer %}
    {% endblock footer %}
  </footer>
</body>